# Test your FastAPI endpoints

GET http://127.0.0.1:8000/hello/Diallo
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json


###

GET http://127.0.0.1:8000/users
Accept: application/json


###

GET http://127.0.0.1:8000/users/1
Accept: application/json


###

POST http://127.0.0.1:8000/users
Accept: application/json

###
